[package]
name = "migration"
version = "0.0.3"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies.sea-orm-migration]
version = "1.1.2"
features = ["sqlx-sqlite", "runtime-tokio-rustls"]
default-features = false
